import { useEffect, useState } from "react";

/* Fleet-console status strip: identity on the left, live telemetry on the
   right, sweep animation riding across it. Same instrument the trader and
   the Jarvis deck wear — this one reports study state instead of positions.

   Every readout is a .hud-seg and the `::` dividers are generated by CSS
   between adjacent segments, so hiding a segment on a narrow screen can't
   strand its separator. The strip is nowrap and overflow:hidden — at 390px
   it was 456px wide and silently cut the clock in half. */
export function HudBar({ view = "", streak = 0, due = 0, classes = 0, tier = "free" }) {
  const [clock, setClock] = useState(() => new Date());

  useEffect(() => {
    const t = setInterval(() => setClock(new Date()), 1000);
    return () => clearInterval(t);
  }, []);

  const time = clock.toLocaleTimeString([], { hour: "numeric", minute: "2-digit", second: "2-digit" });

  return (
    <div className="hud-bar" role="status" aria-label="Study status">
      {/* The identity slot doubles as the nav-bar title. Scrolling the pane
          hands off from the big heading down in the content to this compact
          one — on a wide window it appends after the brand, on a phone it
          takes the brand's place, because a 390px strip has room for one of
          them and the title is the half that tells you where you are. Both
          are always in the DOM; --pane-scroll crossfades them. */}
      <span className="hud-seg hud-title">
        <span className="hud-brand">Scholr</span>
        <span className="hud-view-title"><span className="slash">/</span>{view}</span>
      </span>

      {/* Presence, the plan and the clock are desk furniture: the phone already
          shows the time, and neither of the others changes what you'd tap. */}
      <span className="hud-seg hud-seg-presence">
        <i className="hud-dot online" aria-hidden="true" />
        <span className="hud-opt">Online</span>
      </span>

      <span className="hud-seg">Streak <b className="hud-num">{streak}</b> {streak === 1 ? "day" : "days"}</span>

      <span className="hud-seg">
        <b className={due > 0 ? "hud-num warn" : "hud-num"}>{due > 99 ? "99+" : due}</b> {due === 1 ? "card" : "cards"} to review
      </span>

      <span className="hud-seg hud-opt"><b className="hud-num">{classes}</b> {classes === 1 ? "class" : "classes"}</span>

      <span className="hud-spacer" />

      <span className="hud-seg hud-opt">Plan <b className="hud-num">{tier}</b></span>
      <span className="hud-seg hud-seg-clock"><span className="hud-num">{time}</span></span>
    </div>
  );
}
