import { useNarrow } from "../lib/breakpoints.js";

/* Fleet-console status strip: identity on the left, live telemetry on the
   right, sweep animation riding across it. Same instrument the trader and
   the Jarvis deck wear — this one reports study state instead of positions.

   Every readout is a .hud-seg and the `::` dividers are generated by CSS
   between adjacent segments, so hiding a segment on a narrow screen can't
   strand its separator. The strip is nowrap and overflow:hidden — at 390px
   it was 456px wide and silently cut the clock in half. */
export function HudBar({ view = "", streak = 0, due = 0 }) {
  // The strip is nowrap and overflow:hidden, so anything too wide is silently
  // cut rather than wrapped; "to review" is the short form for phones.
  const narrow = useNarrow();

  return (
    <div className="hud-bar" role="status" aria-label="Study status">
      {/* The identity slot doubles as the nav-bar title. Scrolling the pane
          hands off from the big heading down in the content to this compact
          one — on a wide window it appends after the brand, on a phone it
          takes the brand's place, because a 390px strip has room for one of
          them and the title is the half that tells you where you are. Both
          are always in the DOM; --pane-scroll crossfades them. */}
      <span className="hud-seg hud-title">
        <span className="hud-brand">Scholr</span>
        <span className="hud-view-title"><span className="slash">/</span>{view}</span>
      </span>

      {/* Only what changes what you'd do next. "Online", the class count, the
          plan and a ticking clock were decoration (and the clock re-rendered
          the strip every second). */}
      <span className="hud-seg">Streak <b className="hud-num">{streak}</b> {streak === 1 ? "day" : "days"}</span>

      {due > 0 && (
        <span className="hud-seg">
          <b className="hud-num warn">{due > 99 ? "99+" : due}</b>{" "}
          {narrow ? "to review" : `${due === 1 ? "card" : "cards"} to review`}
        </span>
      )}
    </div>
  );
}
